# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/royce/Downloads/MODS_draft.xpr/MODS/MODS.srcs/sources_1/ip/blk_mem_gen_const/blk_mem_gen_const.xci
# IP: The module: 'blk_mem_gen_const' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/royce/Downloads/MODS_draft.xpr/MODS/MODS.srcs/sources_1/ip/blk_mem_gen_const/blk_mem_gen_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_const'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/royce/Downloads/MODS_draft.xpr/MODS/MODS.srcs/sources_1/ip/blk_mem_gen_const/blk_mem_gen_const.xci
# IP: The module: 'blk_mem_gen_const' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/royce/Downloads/MODS_draft.xpr/MODS/MODS.srcs/sources_1/ip/blk_mem_gen_const/blk_mem_gen_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_const'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
